#!/usr/bin/env python3
"""Rewrite PlantUML code blocks in Markdown into image references."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


BLOCK_RE = re.compile(r"```plantuml\s*\n(.*?)\n```", re.DOTALL)


def load_mapping(path: Path) -> list[dict]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload.get("blocks", [])


def main() -> int:
    parser = argparse.ArgumentParser(description="Replace PlantUML blocks with images.")
    parser.add_argument("source_markdown", help="Path to report.source.md")
    parser.add_argument("mapping_json", help="JSON file generated by render_plantuml.py")
    parser.add_argument("output_markdown", help="Path to report.md")
    args = parser.parse_args()

    source_path = Path(args.source_markdown).resolve()
    mapping_path = Path(args.mapping_json).resolve()
    output_path = Path(args.output_markdown).resolve()

    markdown = source_path.read_text(encoding="utf-8")
    blocks = load_mapping(mapping_path)
    matches = list(BLOCK_RE.finditer(markdown))
    parts = []
    cursor = 0

    for idx, match in enumerate(matches):
        parts.append(markdown[cursor:match.start()])
        block = blocks[idx] if idx < len(blocks) else None
        if block and block.get("status") == "rendered" and block.get("image_path"):
            alt = block.get("title") or f"PlantUML Figure {idx + 1:03d}"
            replacement = f"![{alt}](images/{block['image_path']})"
        else:
            replacement = match.group(0)
        parts.append(replacement)
        cursor = match.end()

    parts.append(markdown[cursor:])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("".join(parts), encoding="utf-8")
    print(
        json.dumps(
            {
                "source_markdown": str(source_path),
                "output_markdown": str(output_path),
                "replaced_blocks": sum(1 for item in blocks if item.get("status") == "rendered"),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
