#!/usr/bin/env python3
import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence


READONLY_FIELD_NAMES = {
    "create_time",
    "created_at",
    "created_by",
    "creator",
    "gmt_create",
}
LOGICAL_DELETE_CANDIDATES = ("deleted", "is_deleted", "del_flag", "status")
TIME_FIELD_KEYWORDS = ("time", "date", "at")
STRING_TYPES = {"char", "varchar", "text", "tinytext", "mediumtext", "longtext"}
NUMBER_TYPES = {
    "tinyint",
    "smallint",
    "int",
    "integer",
    "bigint",
    "decimal",
    "numeric",
    "float",
    "double",
}


class PlannerError(RuntimeError):
    pass


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate CRUD planning JSON from schema JSON.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    plan = subparsers.add_parser("plan", help="Plan CRUD metadata")
    plan.add_argument("--input", required=True, help="Schema JSON generated by db_inspector.py")
    plan.add_argument("--output", help="Optional output JSON file")
    return parser.parse_args(argv)


def camel_case(name: str) -> str:
    pieces = name.split("_")
    return pieces[0] + "".join(piece[:1].upper() + piece[1:] for piece in pieces[1:])


def choose_sort_candidates(columns: List[Dict[str, Any]], primary_key: List[str]) -> List[str]:
    names = [column["name"] for column in columns]
    result: List[str] = []
    for candidate in ("updated_at", "update_time", "gmt_modified", "created_at", "create_time", *primary_key):
        if candidate in names and candidate not in result:
            result.append(candidate)
    if not result:
        result.extend(primary_key[:1])
    return result


def detect_logical_delete_column(columns: List[Dict[str, Any]]) -> Optional[str]:
    names = {column["name"] for column in columns}
    for candidate in LOGICAL_DELETE_CANDIDATES:
        if candidate in names:
            return candidate
    return None


def is_updatable(column: Dict[str, Any], primary_key: List[str]) -> bool:
    name = column["name"]
    if name in primary_key or column["auto_increment"]:
        return False
    if name.lower() in READONLY_FIELD_NAMES:
        return False
    return True


def classify_filter(column: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    name = column["name"]
    data_type = str(column["data_type"]).lower()
    java_type = column.get("java_type", "String")
    if data_type in STRING_TYPES:
        mode = "like" if any(token in name.lower() for token in ("name", "title", "code", "remark", "desc")) else "eq"
    elif data_type in NUMBER_TYPES:
        mode = "range" if any(token in name.lower() for token in ("min", "max", "amount", "count", "score", "price")) else "eq"
    elif any(token in name.lower() for token in TIME_FIELD_KEYWORDS) or java_type in {"LocalDate", "LocalDateTime", "LocalTime"}:
        mode = "between"
    else:
        return None
    return {
        "field": name,
        "param": camel_case(name),
        "operator": mode,
        "java_type": java_type,
    }


def build_where_clause(primary_key: List[str]) -> Optional[str]:
    if not primary_key:
        return None
    return " AND ".join(f"`{column}` = :{camel_case(column)}" for column in primary_key)


def build_insert_sql(table_name: str, columns: List[Dict[str, Any]]) -> Optional[str]:
    writable = [column for column in columns if not column["auto_increment"]]
    if not writable:
        return None
    column_sql = ", ".join(f"`{column['name']}`" for column in writable)
    value_sql = ", ".join(f":{camel_case(column['name'])}" for column in writable)
    return f"INSERT INTO `{table_name}` ({column_sql}) VALUES ({value_sql});"


def build_update_sql(table_name: str, columns: List[Dict[str, Any]], primary_key: List[str]) -> Optional[str]:
    where_clause = build_where_clause(primary_key)
    if not where_clause:
        return None
    assignments = [f"`{column['name']}` = :{camel_case(column['name'])}" for column in columns if is_updatable(column, primary_key)]
    if not assignments:
        return None
    return f"UPDATE `{table_name}` SET {', '.join(assignments)} WHERE {where_clause};"


def build_delete_sql(table_name: str, primary_key: List[str]) -> Optional[str]:
    where_clause = build_where_clause(primary_key)
    if not where_clause:
        return None
    return f"DELETE FROM `{table_name}` WHERE {where_clause};"


def build_logical_delete_sql(table_name: str, primary_key: List[str], logical_delete_column: Optional[str]) -> Optional[str]:
    where_clause = build_where_clause(primary_key)
    if not where_clause or not logical_delete_column:
        return None
    value = "1" if logical_delete_column != "status" else "'DELETED'"
    return f"UPDATE `{table_name}` SET `{logical_delete_column}` = {value} WHERE {where_clause};"


def build_select_page_sql(table_name: str, columns: List[Dict[str, Any]], filters: List[Dict[str, Any]], sort_candidates: List[str]) -> str:
    conditions = ["1 = 1"]
    for item in filters:
        if item["operator"] == "like":
            conditions.append(f"AND `{{field}}` LIKE CONCAT('%', :{{param}}, '%')".format(**item))
        elif item["operator"] == "between":
            conditions.append(
                f"AND `{{field}}` BETWEEN :{{param}}Start AND :{{param}}End".format(**item)
            )
        elif item["operator"] == "range":
            conditions.append(
                f"AND `{{field}}` >= :{{param}}Min AND `{{field}}` <= :{{param}}Max".format(**item)
            )
        else:
            conditions.append(f"AND `{{field}}` = :{{param}}".format(**item))
    order_by = ", ".join(f"`{column}` DESC" for column in sort_candidates) or "`id` DESC"
    select_cols = ", ".join(f"`{column['name']}`" for column in columns)
    return (
        f"SELECT {select_cols} FROM `{table_name}` "
        f"WHERE {' '.join(conditions)} ORDER BY {order_by} LIMIT :offset, :pageSize;"
    )


def build_select_by_pk_sql(table_name: str, columns: List[Dict[str, Any]], primary_key: List[str]) -> Optional[str]:
    where_clause = build_where_clause(primary_key)
    if not where_clause:
        return None
    select_cols = ", ".join(f"`{column['name']}`" for column in columns)
    return f"SELECT {select_cols} FROM `{table_name}` WHERE {where_clause};"


def build_java_field_hints(columns: List[Dict[str, Any]], primary_key: List[str], filters: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    filter_fields = {item["field"] for item in filters}
    hints: List[Dict[str, Any]] = []
    for column in columns:
        hints.append(
            {
                "field": column["name"],
                "java_property": camel_case(column["name"]),
                "java_type": column.get("java_type", "String"),
                "required_on_insert": not column["nullable"] and column["default"] is None and not column["auto_increment"],
                "allowed_on_update": is_updatable(column, primary_key),
                "allowed_as_filter": column["name"] in filter_fields,
            }
        )
    return hints


def summarize_table(table: Dict[str, Any], filters: List[Dict[str, Any]], sort_candidates: List[str], logical_delete_column: Optional[str]) -> str:
    base = "适合标准单表 CRUD" if table["primary_key"] else "缺少主键，更新和删除风险较高"
    filter_desc = f"支持 {len(filters)} 个常用筛选条件" if filters else "筛选字段较少"
    sort_desc = f"推荐按 {sort_candidates[0]} 倒序分页" if sort_candidates else "未识别出明确排序字段"
    delete_desc = f"，可补充基于 `{logical_delete_column}` 的逻辑删除" if logical_delete_column else ""
    return f"{base}，{filter_desc}，{sort_desc}{delete_desc}。"


def build_table_plan(table: Dict[str, Any]) -> Dict[str, Any]:
    columns = table["columns"]
    primary_key = table["primary_key"]
    filters = [item for item in (classify_filter(column) for column in columns) if item]
    sort_candidates = choose_sort_candidates(columns, primary_key)
    logical_delete_column = detect_logical_delete_column(columns)
    risks: List[str] = []
    if not primary_key:
        risks.append("Table has no primary key; update/delete templates are omitted.")
    if len(primary_key) > 1:
        risks.append("Composite primary key detected; caller must provide all key fields.")

    return {
        "table": table["name"],
        "summary": summarize_table(table, filters, sort_candidates, logical_delete_column),
        "risks": risks,
        "primary_key": primary_key,
        "java_field_hints": build_java_field_hints(columns, primary_key, filters),
        "filters": filters,
        "sort_candidates": sort_candidates,
        "query_templates": {
            "select_page": build_select_page_sql(table["name"], columns, filters, sort_candidates),
            "select_by_primary_key": build_select_by_pk_sql(table["name"], columns, primary_key),
            "insert": build_insert_sql(table["name"], columns),
            "update_by_primary_key": build_update_sql(table["name"], columns, primary_key),
            "delete_by_primary_key": build_delete_sql(table["name"], primary_key),
            "logical_delete": build_logical_delete_sql(table["name"], primary_key, logical_delete_column),
        },
    }


def build_summary(table_plans: List[Dict[str, Any]]) -> List[str]:
    lines: List[str] = []
    for item in table_plans:
        lines.append(f"{item['table']}: {item['summary']}")
    return lines


def write_output(payload: Dict[str, Any], output: Optional[str]) -> None:
    rendered = json.dumps(payload, ensure_ascii=False, indent=2)
    if output:
        Path(output).write_text(rendered + "\n", encoding="utf-8")
    else:
        print(rendered)


def main(argv: Optional[Sequence[str]] = None) -> int:
    try:
        args = parse_args(argv)
        payload = json.loads(Path(args.input).read_text(encoding="utf-8"))
        if "tables" not in payload or "connection" not in payload:
            raise PlannerError("Invalid schema JSON: missing `tables` or `connection`.")
        table_plans = [build_table_plan(table) for table in payload["tables"]]
        result = {
            "connection": payload["connection"],
            "table_plans": table_plans,
            "summary": build_summary(table_plans),
            "generated_at": utc_now(),
        }
        write_output(result, args.output)
        return 0
    except (PlannerError, OSError, json.JSONDecodeError) as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
